# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dece4d2c5f1c2b5b2f41b928f8e39a7197f85b40c69947316ee0d68027336abe1bd03490c83a6e6316b5262228e6114bb87d492d9e378fa19b699e4ba3210cda

test:
  secret_key_base: e5ffe3426ffcd4fef5325cb491cefe10546e7311eb14d61779b9bc729eba52378a96addf6f4f6b7217e124a510b09365746aedc9a6d810f56ea8bcc0ed863587

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
